export default {
    UPDATE_USER_DATA: 'UPDATE_USER_DATA',
    ADD_USER_LIST: 'ADD_USER_LIST',
    INIT_USER_DATA: 'INIT_USER_DATA',
    READ_DATA_FROM_DISK: 'READ_DATA_FROM_DISK',
    FETCH_NEWS_LIST: 'FETCH_NEWS_LIST',
}